<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Describing Data with Tables and Graphs – STA 2381 Introductory Statistical Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2ea2d3e7f2364fcda3d434693d3458e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
div.callout-example.callout {
  border-left-color: #008000;
}
div.callout-example.callout-style-default > .callout-header {
  background-color: rgba(0, 128, 0, 0.13);
}
div.callout-example .callout-toggle::before {  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(33, 37, 41)" class="bi bi-chevron-down" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg>');}
div.callout-example.callout-style-default .callout-icon::before, div.callout-example.callout-titled .callout-icon::before {
  content: '📈';
  background-image: none;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href=".center-panel.quarto-layout-panel {
  justify-content: center;
  column-gap: 1rem;
}">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing Data with Tables and Graphs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Collecting Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing Data with Tables and Graphs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Describing Data with Numbers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability Concepts</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-03_01" id="toc-sec-03_01" class="nav-link active" data-scroll-target="#sec-03_01"><span class="header-section-number">3.1</span> Organizing Categorical Data</a>
  <ul class="collapse">
  <li><a href="#frequency-and-relative-frequency-tables" id="toc-frequency-and-relative-frequency-tables" class="nav-link" data-scroll-target="#frequency-and-relative-frequency-tables">Frequency and relative frequency tables</a></li>
  <li><a href="#two-way-contingency-tables" id="toc-two-way-contingency-tables" class="nav-link" data-scroll-target="#two-way-contingency-tables">Two-way (contingency) tables</a></li>
  <li><a href="#why-percentages-matter" id="toc-why-percentages-matter" class="nav-link" data-scroll-target="#why-percentages-matter">Why percentages matter</a></li>
  <li><a href="#working-in-jmp" id="toc-working-in-jmp" class="nav-link" data-scroll-target="#working-in-jmp">Working in JMP</a></li>
  <li><a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap">Recap</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding">Check your understanding</a></li>
  </ul></li>
  <li><a href="#sec-03_02" id="toc-sec-03_02" class="nav-link" data-scroll-target="#sec-03_02"><span class="header-section-number">3.2</span> Bar Charts and Pie Charts</a>
  <ul class="collapse">
  <li><a href="#what-is-a-bar-chart" id="toc-what-is-a-bar-chart" class="nav-link" data-scroll-target="#what-is-a-bar-chart">What is a bar chart?</a></li>
  <li><a href="#design-tips-for-bar-charts" id="toc-design-tips-for-bar-charts" class="nav-link" data-scroll-target="#design-tips-for-bar-charts">Design tips for bar charts</a></li>
  <li><a href="#keep-consistent-spacing" id="toc-keep-consistent-spacing" class="nav-link" data-scroll-target="#keep-consistent-spacing">Keep consistent spacing</a></li>
  <li><a href="#sort-deliberately" id="toc-sort-deliberately" class="nav-link" data-scroll-target="#sort-deliberately">Sort deliberately</a></li>
  <li><a href="#avoid-clutter-and-gimmicks" id="toc-avoid-clutter-and-gimmicks" class="nav-link" data-scroll-target="#avoid-clutter-and-gimmicks">Avoid clutter and gimmicks</a></li>
  <li><a href="#why-these-rules-matter" id="toc-why-these-rules-matter" class="nav-link" data-scroll-target="#why-these-rules-matter">Why these rules matter</a></li>
  <li><a href="#what-is-a-pie-chart" id="toc-what-is-a-pie-chart" class="nav-link" data-scroll-target="#what-is-a-pie-chart">What is a pie chart?</a></li>
  <li><a href="#when-to-use-bar-charts-vs.-pie-charts" id="toc-when-to-use-bar-charts-vs.-pie-charts" class="nav-link" data-scroll-target="#when-to-use-bar-charts-vs.-pie-charts">When to use bar charts vs.&nbsp;pie charts</a></li>
  <li><a href="#a-practical-rule-of-thumb" id="toc-a-practical-rule-of-thumb" class="nav-link" data-scroll-target="#a-practical-rule-of-thumb">A practical rule of thumb</a></li>
  <li><a href="#clustered-and-stacked-bar-charts" id="toc-clustered-and-stacked-bar-charts" class="nav-link" data-scroll-target="#clustered-and-stacked-bar-charts">Clustered and stacked bar charts</a></li>
  <li><a href="#working-in-jmp-1" id="toc-working-in-jmp-1" class="nav-link" data-scroll-target="#working-in-jmp-1">Working in JMP</a></li>
  <li><a href="#recap-1" id="toc-recap-1" class="nav-link" data-scroll-target="#recap-1">Recap</a></li>
  <li><a href="#check-your-understanding-1" id="toc-check-your-understanding-1" class="nav-link" data-scroll-target="#check-your-understanding-1">Check your understanding</a></li>
  </ul></li>
  <li><a href="#sec-03_03" id="toc-sec-03_03" class="nav-link" data-scroll-target="#sec-03_03"><span class="header-section-number">3.3</span> Organizing Quantitative Data</a>
  <ul class="collapse">
  <li><a href="#constructing-frequency-distributions" id="toc-constructing-frequency-distributions" class="nav-link" data-scroll-target="#constructing-frequency-distributions">Constructing frequency distributions</a></li>
  <li><a href="#relative-and-cumulative-frequencies" id="toc-relative-and-cumulative-frequencies" class="nav-link" data-scroll-target="#relative-and-cumulative-frequencies">Relative and cumulative frequencies</a></li>
  <li><a href="#choosing-the-number-of-classes" id="toc-choosing-the-number-of-classes" class="nav-link" data-scroll-target="#choosing-the-number-of-classes">Choosing the number of classes</a></li>
  <li><a href="#working-in-jmp-2" id="toc-working-in-jmp-2" class="nav-link" data-scroll-target="#working-in-jmp-2">Working in JMP</a></li>
  <li><a href="#recap-2" id="toc-recap-2" class="nav-link" data-scroll-target="#recap-2">Recap</a></li>
  <li><a href="#check-your-understanding-2" id="toc-check-your-understanding-2" class="nav-link" data-scroll-target="#check-your-understanding-2">Check your understanding</a></li>
  </ul></li>
  <li><a href="#sec-03_4" id="toc-sec-03_4" class="nav-link" data-scroll-target="#sec-03_4"><span class="header-section-number">3.4</span> Histograms, Stem‑and‑Leaf Plots, and Dotplots</a>
  <ul class="collapse">
  <li><a href="#histograms" id="toc-histograms" class="nav-link" data-scroll-target="#histograms">Histograms</a></li>
  <li><a href="#why-histograms-matter" id="toc-why-histograms-matter" class="nav-link" data-scroll-target="#why-histograms-matter">Why histograms matter</a></li>
  <li><a href="#stem-and-leaf-plots" id="toc-stem-and-leaf-plots" class="nav-link" data-scroll-target="#stem-and-leaf-plots">Stem-and-leaf plots</a></li>
  <li><a href="#when-stem-and-leaf-plots-are-most-useful" id="toc-when-stem-and-leaf-plots-are-most-useful" class="nav-link" data-scroll-target="#when-stem-and-leaf-plots-are-most-useful">When stem-and-leaf plots are most useful</a></li>
  <li><a href="#dotplots" id="toc-dotplots" class="nav-link" data-scroll-target="#dotplots">Dotplots</a></li>
  <li><a href="#when-dotplots-are-most-useful" id="toc-when-dotplots-are-most-useful" class="nav-link" data-scroll-target="#when-dotplots-are-most-useful">When dotplots are most useful</a></li>
  <li><a href="#choosing-the-right-display" id="toc-choosing-the-right-display" class="nav-link" data-scroll-target="#choosing-the-right-display">Choosing the right display</a></li>
  <li><a href="#working-in-jmp-3" id="toc-working-in-jmp-3" class="nav-link" data-scroll-target="#working-in-jmp-3">Working in JMP</a></li>
  <li><a href="#recap-3" id="toc-recap-3" class="nav-link" data-scroll-target="#recap-3">Recap</a></li>
  <li><a href="#check-your-understanding-3" id="toc-check-your-understanding-3" class="nav-link" data-scroll-target="#check-your-understanding-3">Check your understanding</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing Data with Tables and Graphs</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-03_01" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-03_01"><span class="header-section-number">3.1</span> Organizing Categorical Data</h2>
<blockquote class="blockquote">
<p>“The greatest value of a picture is when it forces us to notice what we never expected to see.” – John Tukey</p>
</blockquote>
<p>When you collect data that fall into groups—like preferred streaming service, political affiliation, or type of pet—the first step is to count how many observations fall into each category. Those counts form the backbone of both tables and graphs for categorical data. In this section we’ll learn how to build simple frequency tables, translate them into proportions or percentages, and organize two categorical variables together in a two‑way table. Along the way we’ll see when different visual summaries make sense and preview bar and pie charts (covered in detail in <a href="#sec-03_02" class="quarto-xref"><span>Section 3.2</span></a>).</p>
<section id="frequency-and-relative-frequency-tables" class="level3">
<h3 class="anchored" data-anchor-id="frequency-and-relative-frequency-tables">Frequency and relative frequency tables</h3>
<p>A <strong>frequency table</strong> is a basic but powerful tool for summarizing a <strong>categorical variable</strong>. It lists each distinct category and records how many observations fall into that category. By organizing raw data into counts, a frequency table provides an immediate snapshot of how the data are distributed across categories, making patterns and imbalances easy to see.</p>
<p>A typical frequency table has two columns: one for the category labels and one for their <strong>frequencies</strong> (counts). Constructing a frequency table involves identifying all possible categories and tallying the number of observations in each. This process is often the first step in data analysis because it reduces a potentially large and messy dataset into a clear and interpretable summary.</p>
<p>While frequency tables report absolute counts, these counts can be misleading when sample sizes differ. For example, a category with 50 observations may seem large, but its importance depends on whether the total sample size is 100 or 1,000. To address this, we often compute <strong>relative frequencies</strong>.</p>
<p>A <strong>relative frequency</strong> expresses the count for each category as a proportion of the total number of observations. When a column of relative frequencies—or percentages—is added to a frequency table, the result is called a <strong>relative frequency table</strong>. Relative frequencies are calculated by dividing each category’s count by the total sample size. Because they represent proportions of the whole, relative frequencies always sum to 1 (or 100% when expressed as percentages).</p>
<p>Relative frequency tables are especially useful for <strong>comparing distributions across different samples or populations</strong>. By focusing on proportions rather than raw counts, they allow meaningful comparisons even when the underlying sample sizes are not the same. For this reason, relative frequencies are commonly used in reports, visualizations, and summaries intended for broad audiences.</p>
<p>In practice, frequency and relative frequency tables often serve as the foundation for graphical displays such as bar charts and pie charts, providing a clear numerical summary that complements visual representations of categorical data.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.1: Common symptoms in a clinic
</div>
</div>
<div class="callout-body-container callout-body">
<p>Imagine you survey 30 patients at a local clinic about the primary symptom that brought them in. You record four categories: “Headache,” “Back pain,” “Fatigue,” and “Nausea.” We can organize the responses in a simple table of counts and proportions. Below we simulate such a survey and display the results.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">response</th>
<th style="text-align: right;">frequency</th>
<th style="text-align: right;">relative_frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Back pain</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.3000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fatigue</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.3000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Headache</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.2666667</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nausea</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.1333333</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The table lists the four categories in alphabetical order with their counts and relative frequencies. For instance, if 8 of the 30 patients reported “Headache,” the relative frequency of “Headache” is <span class="math inline">\(8/30 \approx 0.27\)</span>. The accompanying bar chart gives a visual sense of the same information: each bar’s height corresponds to a category’s frequency, and the bars are separated to emphasize that the categories have no inherent order. In practice you might reorder the bars to make the graph easier to read—perhaps putting the largest category first.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Pareto charts">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pareto charts
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Sometimes you want to highlight the few categories that account for most of the observations. A <strong>Pareto chart</strong> is a bar chart arranged in descending order of frequency and often paired with a cumulative percentage line. It helps you identify the “vital few and trivial many” in quality control and business applications. Pareto charts are useful when there are many categories and you want to focus attention on the most common causes or responses.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>In JMP you can create a frequency table by selecting <strong>Analyze → Distribution</strong>, assigning your categorical variable to the X role, and examining the resulting counts. To add relative frequencies, use the red triangle menu (▸) to choose <strong>Display Options → Show Percent</strong>. JMP’s Graph Builder will automatically construct a bar chart when you drag a categorical variable to the X‑axis and the count statistic to the Y‑axis.</p>
</div>
</div>
</div>
</section>
<section id="two-way-contingency-tables" class="level3">
<h3 class="anchored" data-anchor-id="two-way-contingency-tables">Two-way (contingency) tables</h3>
<p>When data include two categorical variables, a natural question is whether—and how—those variables are related. A <strong>two-way table</strong>, also called a <strong>contingency table</strong>, provides a clear way to summarize and explore this relationship. Rather than listing categories separately, a contingency table displays the <em>counts for every combination</em> of categories across the two variables.</p>
<p>In a contingency table, one categorical variable defines the <em>rows</em> and the other defines the <em>columns</em>. Each cell in the table shows how many observations fall into the corresponding pair of categories. The table also often includes <em>row totals</em>, <em>column totals</em>, and a <em>grand total</em>, which help place the individual cell counts in context.</p>
<p>Contingency tables are especially useful for examining <strong>associations</strong> between variables. By comparing counts or proportions across rows or columns, you can look for patterns such as whether certain categories tend to occur together more often than would be expected by chance. For example, you might ask whether voting preference differs by age group, or whether product satisfaction varies by subscription type.</p>
<p>To aid interpretation, contingency tables are often converted to <strong>conditional distributions</strong> by computing row or column percentages. Row percentages answer questions like “Given this row category, how are observations distributed across the columns?” Column percentages reverse the conditioning. Choosing which percentages to compute depends on the research question and which variable is considered explanatory versus response.</p>
<p>Contingency tables form the foundation for formal statistical analysis of categorical data. In later chapters, these tables will provide the structure for chi-square tests of independence, which assess whether the observed association between two categorical variables is stronger than would be expected from random variation alone. Even before formal testing, however, contingency tables offer a powerful descriptive tool for uncovering relationships in categorical data.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.2: symptom by age group
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we collect data on the same symptom question but also record each patient’s age group: “Under 30,” “30–50,” or “Over 50.” We can summarize the joint distribution in a two‑way table.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">age_group</th>
<th style="text-align: right;">Back pain</th>
<th style="text-align: right;">Fatigue</th>
<th style="text-align: right;">Headache</th>
<th style="text-align: right;">Nausea</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">30–50</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Over 50</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Under 30</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each cell in the table shows the number of patients who fall into the corresponding combination of age group and symptom. We can also compute row or column relative frequencies to see percentages within each group; for example, dividing each row by its total gives the distribution of symptoms within each age group. Contingency tables allow us to see whether symptom patterns differ across age groups and serve as input for clustered or stacked bar charts (discussed in Section 3.2).</p>
</div>
</div>
</section>
<section id="why-percentages-matter" class="level3">
<h3 class="anchored" data-anchor-id="why-percentages-matter">Why percentages matter</h3>
<p>Because categorical variables can have different numbers of levels and sample sizes can vary, relative frequencies are essential for fair comparisons. Reporting only counts can be misleading: 20 supporters of a movie genre in a survey of 50 people represent a large fraction, while 20 supporters in a survey of 500 people represent a much smaller fraction. Percentages standardize the scale.</p>
<p>When displaying percentages, make sure they add to 100%. In a pie chart (a circular graph we’ll describe in the next section), each slice represents a category’s percentage of the whole. Pie charts are useful for showing how the total is divided among categories, but they become cluttered with too many slices. Bar charts are more flexible: you can reorder the bars, show counts or percentages, and compare multiple groups using side‑by‑side or stacked bars.</p>
</section>
<section id="working-in-jmp" class="level3">
<h3 class="anchored" data-anchor-id="working-in-jmp">Working in JMP</h3>
<p>In JMP, tables and graphs for categorical variables are straightforward:</p>
<ul>
<li>To create a frequency table, go to <strong>Analyze → Distribution</strong>, assign your categorical variable to <strong>X</strong>, and click <strong>OK</strong>. The report shows counts and percentages; use the red triangle (▸) menu to toggle percentages, counts, or both.</li>
<li>For two categorical variables, use <strong>Analyze → Fit Y by X</strong> and assign one variable to Y and the other to X. Choose <strong>Contingency Table</strong> from the platform to see the two‑way counts and associated statistics.</li>
<li>To visualize categorical distributions, open <strong>Graph Builder</strong>, drag the categorical variable to the X‑axis, and drop the <strong>N</strong> summary statistic onto the Y‑axis. You can change the chart type to “Bar” or “Pie.” Dragging a second categorical variable onto the <strong>Group</strong> drop zone will create clustered or stacked bars.</li>
</ul>
</section>
<section id="recap" class="level3">
<h3 class="anchored" data-anchor-id="recap">Recap</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 81%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Keyword</strong></th>
<th><strong>Definition</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Frequency table</strong></td>
<td>A table that lists each category of a variable and the number of observations in that category.</td>
</tr>
<tr class="even">
<td><strong>Relative frequency</strong></td>
<td>The proportion or percentage of observations in a category, equal to the category’s count divided by the total count.</td>
</tr>
<tr class="odd">
<td><strong>Relative frequency table</strong></td>
<td>A frequency table with an additional column showing the relative frequency of each category.</td>
</tr>
<tr class="even">
<td><strong>Two‑way (contingency) table</strong></td>
<td>A table that displays the counts for each combination of levels of two categorical variable.</td>
</tr>
</tbody>
</table>
</section>
<section id="check-your-understanding" class="level3">
<h3 class="anchored" data-anchor-id="check-your-understanding">Check your understanding</h3>
<div class="callout callout-style-default callout-note callout-titled" title="Problems">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problems
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>In a survey of 80 households, 32 own a dog, 20 own a cat, 12 own both, and the remainder own no pets. Construct a frequency table that shows the number and percentage of households in each pet ownership category (Dog only, Cat only, Both, None). Which visualization—a bar chart or a pie chart—would you choose, and why?</p></li>
<li><p>Explain the difference between a frequency table and a relative frequency table. In what situations is it more informative to look at relative frequencies rather than absolute frequencies?</p></li>
<li><p>What is a two‑way (contingency) table? Describe a scenario where a two‑way table could help you explore the relationship between two categorical variables.</p></li>
<li><p>Bar charts have spaces between bars and can be drawn in any order. Why are these design choices appropriate for categorical variables? What might go wrong if you drew the bars touching or forced them into a numerical order?</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Pet ownership table.</strong> The four categories and their counts are: Dog only (20), Cat only (8), Both (12), None (40). The total number of households is 80. The relative frequencies are 25% dog only, 10% cat only, 15% both, and 50% none. A bar chart would be preferable here because it allows you to order the bars from most to least common and makes it easy to compare magnitudes. A pie chart could work for four categories, but it becomes harder to read when slices are similar in size or when there are many categories.</p></li>
<li><p><strong>Frequency vs.&nbsp;relative frequency.</strong> A frequency table reports the counts of observations in each category. A relative frequency table adds a column showing the proportion or percentage of observations in each category. Relative frequencies are more informative when comparing groups of different sizes or when you want to focus on the distribution rather than the sample size—for example, comparing survey results from two classes of different sizes.</p></li>
<li><p><strong>Contingency table example.</strong> A two‑way table displays counts for each combination of levels of two categorical variable. For instance, you could record whether each patient in a clinic has insurance (Yes/No) and whether they arrived on time (On time/Late). A contingency table would show how many patients fall into each combination (e.g., insured &amp; on time, insured &amp; late, uninsured &amp; on time, uninsured &amp; late), helping you explore whether punctuality differs by insurance status.</p></li>
<li><p><strong>Design choices.</strong> Categories have no intrinsic numeric order, so bars in a bar chart can be arranged in any order without misrepresenting the data. Leaving space between bars reinforces that the categories are distinct and unordered. If you drew the bars touching, it might suggest a continuous scale (like a histogram), which could confuse readers. Forcing categories into a numerical order might imply ranking where none exists.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="sec-03_02" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-03_02"><span class="header-section-number">3.2</span> Bar Charts and Pie Charts</h2>
<blockquote class="blockquote">
<p>“Normally if given a choice between doing something and nothing, I’d choose to do nothing. But I would do something if it helps someone do nothing. I’d work all night if it meant nothing got done.” – Ron Swanson</p>
</blockquote>
<p>When you’ve tallied the counts of a categorical variable, your next job is to turn those numbers into a picture. Two of the simplest pictures—<em>bar charts</em> and <em>pie charts</em>—seem deceptively alike: each shows categories and their sizes. But as we’ll see, they serve different purposes and come with different design rules.</p>
<section id="what-is-a-bar-chart" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-bar-chart">What is a bar chart?</h3>
<p>As we have already seen in <a href="#sec-03_01" class="quarto-xref"><span>Section 3.1</span></a>, a <strong>bar chart</strong> is one of the most common and effective ways to visualize <em>categorical data</em>. It displays distinct categories along one axis and represents a numerical value for each category—such as a count, proportion, or percentage—using the length of a bar along the other axis. Bar charts can be drawn with bars oriented vertically (often called <em>column charts</em>) or horizontally, depending on which layout best supports readability.</p>
<p>A defining feature of bar charts is that the bars are <em>separated by gaps</em>. These gaps signal that the categories are discrete and unordered, distinguishing bar charts from histograms, which display continuous data with adjacent bins. The axis along which the bars extend typically starts at zero, ensuring that bar lengths accurately reflect the magnitudes being compared.</p>
<p>Bar charts are especially effective because humans are very good at comparing lengths that share a <em>common baseline</em>. This makes it easy to see which categories are larger or smaller, to compare differences across groups, and to identify patterns or outliers at a glance. For this reason, bar charts are a natural choice for summarizing frequency tables, relative frequency tables, and summary statistics across categories.</p>
<p>Bar charts are also flexible. They can be used to display raw counts, percentages, averages, or other summary measures, as long as the underlying variable is categorical. When categories have long labels or there are many of them, horizontal bar charts often improve readability. In more advanced settings, grouped or stacked bar charts can be used to compare categories across additional variables.</p>
<p>Because of their clarity and versatility, bar charts are often the first visualization used to explore categorical data and to communicate results to a broad audience.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.3: Distribution of blood types
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a hospital records the blood type (A, B, AB or O) of 200 randomly chosen donors. The counts are shown in the table below along with a bar chart. Notice that the bars are separated and can be reordered to make patterns easy to see.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">type</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">prop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">0.330</td>
</tr>
<tr class="even">
<td style="text-align: left;">AB</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.045</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.155</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">0.470</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The vertical bar chart emphasizes how common type O is relative to the others. You could flip the axes to make a horizontal bar chart if your category names are long or if you prefer to read labels on the y‑axis.</p>
</div>
</div>
</section>
<section id="design-tips-for-bar-charts" class="level3">
<h3 class="anchored" data-anchor-id="design-tips-for-bar-charts">Design tips for bar charts</h3>
<p>Bar charts are powerful because they encode values using <strong>length</strong>, which humans perceive accurately when bars share a common baseline. Poor design choices can undermine that strength and unintentionally (or intentionally) mislead the reader. The following guidelines help ensure that bar charts communicate information honestly and clearly.</p>
<section id="start-the-axis-at-zero" class="level4">
<h4 class="anchored" data-anchor-id="start-the-axis-at-zero">Start the axis at zero</h4>
<p>Because bar charts represent magnitude through bar length, the axis should almost always start at <strong>zero</strong>. Truncating the axis exaggerates differences by making small changes appear visually dramatic. While truncated axes are sometimes acceptable for line charts, they are almost always misleading for bar charts.</p>
<p><strong>What goes wrong if you don’t:</strong> Two categories with similar values may appear drastically different, leading readers to overestimate the importance of the difference.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="keep-consistent-spacing" class="level3">
<h3 class="anchored" data-anchor-id="keep-consistent-spacing">Keep consistent spacing</h3>
<p>Bars should be evenly spaced, with visible gaps between them. The gaps reinforce that categories are <strong>discrete</strong>, not continuous, and help the eye separate groups cleanly.</p>
<p><strong>What goes wrong if you don’t:</strong> Inconsistent or missing gaps can make bars blend together, confusing the chart with a histogram or suggesting unintended relationships.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sort-deliberately" class="level3">
<h3 class="anchored" data-anchor-id="sort-deliberately">Sort deliberately</h3>
<p>The order of bars should help the reader understand the data. Common choices include <strong>alphabetical order</strong>, <strong>chronological order</strong>, or <strong>ordering by value</strong>. A deliberate ordering allows patterns and comparisons to emerge naturally.</p>
<p><strong>What goes wrong if you don’t:</strong> Random or arbitrary ordering forces the reader to work harder and can hide meaningful trends.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="avoid-clutter-and-gimmicks" class="level3">
<h3 class="anchored" data-anchor-id="avoid-clutter-and-gimmicks">Avoid clutter and gimmicks</h3>
<p>Decorative elements—such as 3-D bars, shadows, gradients, icons, or excessive labels—do not add information. Instead, they distort perception, make values harder to compare, and distract from the data itself.</p>
<p><strong>What goes wrong if you don’t:</strong> 3-D effects change apparent bar lengths depending on viewing angle, and visual clutter overwhelms the message.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="why-these-rules-matter" class="level3">
<h3 class="anchored" data-anchor-id="why-these-rules-matter">Why these rules matter</h3>
<p>Each of these principles protects the integrity of the visual message. Bar charts are most effective when they are <strong>simple, proportional, and transparent</strong>. Violating these guidelines can exaggerate differences, obscure patterns, or mislead readers—sometimes unintentionally, sometimes not.</p>
<p>Following these design tips ensures that your bar charts support accurate interpretation and reinforce, rather than undermine, the credibility of your analysis.</p>
</section>
<section id="what-is-a-pie-chart" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-pie-chart">What is a pie chart?</h3>
<p>A <strong>pie chart</strong> is a graphical display used to show how a <em>whole is divided into parts</em>. The entire circle represents the total—typically 100% of the observations—and each <em>slice</em> corresponds to a category within a categorical variable. The size of each slice is proportional to the category’s share of the total, with larger proportions occupying larger angles and areas of the circle.</p>
<p>Pie charts are widely recognized and easy to interpret at a glance. Their circular shape immediately signals a “part-of-a-whole” relationship, making them intuitive for audiences without formal statistical training. For this reason, pie charts are often used in presentations, reports, and media when the goal is to convey how a total is allocated across a small number of categories.</p>
<p>However, pie charts have important limitations. Human perception is better at comparing <em>lengths along a common baseline</em> than comparing angles or areas. As a result, it can be difficult to judge small differences between slices, especially when categories have similar proportions or when the chart contains many slices. Labels can also become crowded as the number of categories increases.</p>
<p>Because of these limitations, pie charts work best when:</p>
<ul>
<li>There are only a few categories,</li>
<li>The proportions differ substantially,</li>
<li>The goal is to emphasize the overall composition rather than precise comparisons.</li>
</ul>
<p>In situations where accurate comparison across categories is important, a bar chart often provides a clearer and more informative alternative. Nonetheless, when used sparingly and appropriately, pie charts can be an effective way to communicate simple part-whole relationships.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.4: Reasons for missing an appointment
</div>
</div>
<div class="callout-body-container callout-body">
<p>A dental clinic tracks why patients miss scheduled cleanings. Out of 100 missed appointments, 50 were due to forgetfulness, 20 to fear, 15 to cost, and 15 to other reasons. A pie chart makes the share of each reason obvious.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The slices emphasize that half of the missed appointments were simply forgotten. However, imagine adding three more reasons of similar size. The slices would become crowded and hard to compare. Pie charts work only when the categories sum to a meaningful whole and there are no more than a few slices.</p>
</div>
</div>
</section>
<section id="when-to-use-bar-charts-vs.-pie-charts" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use-bar-charts-vs.-pie-charts">When to use bar charts vs.&nbsp;pie charts</h3>
<p>Although the same categorical data can often be displayed using either a bar chart or a pie chart, the two serve <em>different analytical purposes</em> and are not interchangeable. Choosing the right chart depends on what you want the reader to notice and compare.</p>
<section id="use-a-bar-chart-when-you-want-to" class="level4">
<h4 class="anchored" data-anchor-id="use-a-bar-chart-when-you-want-to">Use a <strong>bar chart</strong> when you want to:</h4>
<ul>
<li><p><strong>Compare values across categories or between groups.</strong> Bar charts place values along a common baseline, making differences in magnitude easy to see. This is especially important when categories have similar values or when precise comparisons matter, such as comparing approval ratings across departments or test scores across teaching methods.</p></li>
<li><p><strong>Display statistics that do not form a meaningful whole.</strong> Many summary statistics—such as averages, medians, rates, or scores—do not add up to 100% and therefore do not represent parts of a single total. A pie chart would be inappropriate in these cases, while a bar chart can display these values clearly and honestly.</p></li>
<li><p><strong>Show many categories, even if some are small.</strong> Bar charts remain readable with a large number of categories, particularly when sorted or displayed horizontally. Small values can still be compared accurately, whereas tiny pie slices are difficult to see and label.</p></li>
</ul>
<p>Because bar charts rely on length comparisons, they align well with how people naturally judge quantity, making them the default choice for most categorical comparisons.</p>
</section>
<section id="use-a-pie-chart-only-when" class="level4">
<h4 class="anchored" data-anchor-id="use-a-pie-chart-only-when">Use a <strong>pie chart</strong> only when:</h4>
<ul>
<li><p><strong>The values represent parts of a whole that add up to 100%.</strong> Pie charts are specifically designed to show how a total is divided among categories. If the data do not represent proportions of a single whole, a pie chart is misleading.</p></li>
<li><p><strong>The number of categories is small.</strong> Pie charts work best with a limited number of slices—ideally no more than four or five. Too many slices make the chart cluttered and difficult to interpret.</p></li>
<li><p><strong>The goal is to communicate the overall composition, not precise differences.</strong> Pie charts are effective for conveying the big picture—such as showing that one category dominates the total—rather than for comparing closely sized categories.</p></li>
</ul>
</section>
</section>
<section id="a-practical-rule-of-thumb" class="level3">
<h3 class="anchored" data-anchor-id="a-practical-rule-of-thumb">A practical rule of thumb</h3>
<p>If you find yourself <em>squinting at a pie chart</em> to decide which slice is larger, that’s a sign the chart is doing too much. In those cases, switch to a bar chart. Because humans are far better at judging lengths than angles or areas, bar charts almost always provide clearer and more accurate comparisons.</p>
<p>In practice, bar charts should be your default choice, with pie charts reserved for simple, high-level part-of-a-whole messages.</p>
</section>
<section id="clustered-and-stacked-bar-charts" class="level3">
<h3 class="anchored" data-anchor-id="clustered-and-stacked-bar-charts">Clustered and stacked bar charts</h3>
<p>Sometimes you have two categorical variables and want to see how their categories interact. We introduced two‑way tables in <a href="#sec-03_01" class="quarto-xref"><span>Section 3.1</span></a>; here’s how to graph them.</p>
<p>A <strong>clustered (side‑by‑side) bar chart</strong> groups bars for each level of a second variable next to each other so you can compare across groups. For example, imagine you survey 120 patients about how satisfied they were with a new physical therapy program (satisfied, neutral, dissatisfied) and record whether they were in the treatment or control group. A clustered bar chart shows differences in satisfaction between the two groups.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>In a <strong>stacked bar chart</strong>, bars for each category are stacked atop one another. This emphasizes the total size of each category but makes it harder to compare the segments across stacks. You might use a stacked chart to show how types of injuries (sprain, fracture, other) contribute to emergency visits across departments; if you convert each bar to 100% of its height, you get a <em>100% stacked bar chart</em> that highlights composition within each group.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<section id="cautions-with-stacked-bars" class="level4">
<h4 class="anchored" data-anchor-id="cautions-with-stacked-bars">Cautions with stacked bars</h4>
<p>Stacked bars are useful when you care about the total across categories, but they hide patterns in the middle segments. In the last plot, you can easily compare the overall emergency visits across departments and the share of fractures, but it’s harder to compare the “other” injuries across departments because their segments float at different heights. If your goal is to compare subgroups, a clustered bar chart is usually better.</p>
</section>
</section>
<section id="working-in-jmp-1" class="level3">
<h3 class="anchored" data-anchor-id="working-in-jmp-1">Working in JMP</h3>
<p>In JMP, bar and pie charts live in the <strong>Graph Builder</strong>. Drag your categorical variable to the X‑axis and drop the <strong>N</strong> or <strong>%</strong> statistic onto the Y‑axis to create a bar chart. To cluster by a second categorical variable, drop it in the <strong>Group</strong> or <strong>Overlay</strong> zone, and choose <em>Bar (Horizontal)</em> or <em>Bar (Vertical)</em> from the chart palette. To stack, use the <strong>Stack</strong> option in the legend. To make a pie chart, drag the categorical variable to a blank canvas and choose <em>Pie</em>; JMP will automatically convert counts to percentages and label the slices. Use the red triangle (▸) menu to display data labels, reorder slices, or combine small categories into an “Other” slice.</p>
</section>
<section id="recap-1" class="level3">
<h3 class="anchored" data-anchor-id="recap-1">Recap</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 88%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Keyword/Concept</strong></th>
<th><strong>Definition or note</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Bar chart</strong></td>
<td>Graph that displays categories along one axis and uses the length of bars to represent numeric values; great for comparing counts or percentages across categories.</td>
</tr>
<tr class="even">
<td><strong>Pie chart</strong></td>
<td>Circular chart in which slices represent how a total is divided among categories; appropriate only when values sum to a meaningful whole and the number of categories is small.</td>
</tr>
<tr class="odd">
<td><strong>Clustered (side‑by‑side) bar chart</strong></td>
<td>Bar chart where categories are grouped side by side for levels of a second variable; useful for comparing groups across categories.</td>
</tr>
<tr class="even">
<td><strong>Stacked bar chart</strong></td>
<td>Bar chart where bars for each subgroup are stacked; shows composition and totals but makes it harder to compare individual segments.</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="check-your-understanding-1" class="level3">
<h3 class="anchored" data-anchor-id="check-your-understanding-1">Check your understanding</h3>
<div class="callout callout-style-default callout-note callout-titled" title="Problems">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problems
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>A clinical trial reports the average pain score (on a 0–10 scale) for three physical therapy programs. Should you use a bar chart or a pie chart? Explain your reasoning.</p></li>
<li><p>A nutritionist surveys 500 patients about their preferred breakfast type: cereal, fruit, eggs, or none. The counts are 150, 120, 80, and 150. Sketch how you would display this information with a pie chart. When might a bar chart be preferable?</p></li>
<li><p>In a mental health study, participants are classified into stress levels (low, moderate, high) and whether they attended counseling (Yes/No). Which type of bar chart would you use to compare stress levels between counseling and non‑counseling participants? What pattern would indicate that counseling is associated with lower stress?</p></li>
<li><p>A bar chart shows the average number of cavities per patient in three dental clinics: 1.2, 1.3 and 1.4 cavities. The y‑axis starts at 1.0. Explain why this design might mislead and how to fix it.</p></li>
<li><p>Give two reasons why pie charts often make it harder to compare categories than bar charts.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>You should use a <strong>bar chart</strong> because the numbers represent average pain scores and do not sum to a meaningful whole. Pie charts imply a part‑to‑whole relationship and would be misleading here.</p></li>
<li><p>The four breakfast types form parts of the whole sample (500 patients). In a pie chart, the slices would be 30% cereal, 24% fruit, 16% eggs, and 30% none. However, a bar chart may be preferable because it allows you to order the categories from most to least common and makes it easier to compare the cereal and none categories, which are equal in size.</p></li>
<li><p>A <strong>clustered (side‑by‑side) bar chart</strong> would let you compare the counts (or proportions) of low, moderate, and high stress within the counseling and non‑counseling groups. If counseling is associated with lower stress, you would expect the “low” bar to be taller (or the “high” bar shorter) in the counseling group than in the non‑counseling group.</p></li>
<li><p>Starting the y‑axis at 1.0 truncates the bars and exaggerates small difference. To avoid misleading readers, start the axis at zero. Alternatively, use a dot plot or annotate the differences directly if the differences are small but meaningful.</p></li>
<li><p>First, people judge lengths more accurately than angles; in a pie chart it is hard to gauge the exact size of a slice. Second, when slices are similar in size or there are many categories, comparing slices becomes difficult and the chart becomes cluttered. Bar charts avoid these issues by using a common baseline and allowing many bars.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="sec-03_03" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-03_03"><span class="header-section-number">3.3</span> Organizing Quantitative Data</h2>
<blockquote class="blockquote">
<p>“It’s not what you look at that matters, it’s what you see.” - Henry David Thoreau</p>
</blockquote>
<p>Categorical variables describe membership in distinct groups, but <strong>quantitative variables</strong> operate on an entirely different scale. Measurements such as height, blood pressure, cholesterol level, income, or reaction time can take on a wide range of numerical values along a continuum. When presented as a raw list, these numbers are often difficult to interpret on their own.</p>
<p>To extract meaning from quantitative data, we must <em>organize and summarize</em> it in a systematic way. One of the most effective approaches is to group numerical values into intervals and display the results in tables. These tables provide a structured summary of the data and serve as the foundation for graphical displays such as <strong>histograms</strong>, <strong>stem-and-leaf plots</strong>, and <strong>dotplots</strong>.</p>
<p>Well-constructed tables help reveal key features of a distribution. They show where values tend to cluster, how widely the data are spread, and how observations accumulate across the range of possible values. By organizing quantitative data before visualizing it, we gain insight into its overall shape and structure that raw numbers alone rarely provide.</p>
<section id="constructing-frequency-distributions" class="level3">
<h3 class="anchored" data-anchor-id="constructing-frequency-distributions">Constructing frequency distributions</h3>
<p>A <strong>frequency distribution</strong> for quantitative data is a table that organizes numerical values into a set of <em>non-overlapping intervals</em>, called <strong>classes</strong>, and records how many observations fall into each class. Instead of examining individual data points one by one, a frequency distribution provides a structured summary that reveals the overall pattern of the data.</p>
<p>Each class is defined by a <em>lower limit</em> and an <em>upper limit</em>, and together the classes cover the entire range of the dataset. The <em>class width</em> is the distance between consecutive class boundaries (or lower limits), and the <em>range</em> of the data is the difference between the maximum and minimum observed values. Thoughtful choices about the number of classes and their widths are essential: too few classes hide important structure, while too many classes make the table overly detailed and difficult to interpret.</p>
<p>The purpose of a frequency distribution is not to preserve every detail, but to highlight the <strong>shape</strong>, <strong>center</strong>, and <strong>spread</strong> of the data in a compact and interpretable form.</p>
<section id="steps-for-constructing-a-frequency-distribution" class="level4">
<h4 class="anchored" data-anchor-id="steps-for-constructing-a-frequency-distribution">Steps for constructing a frequency distribution</h4>
<ol type="1">
<li><p><strong>Decide on the number of classes.</strong> A common guideline is to use between <em>5 and 20 classes</em>. Fewer classes may oversimplify the distribution, masking important features such as skewness or multiple peaks. Too many classes, on the other hand, can make the distribution appear noisy and obscure the overall pattern.</p></li>
<li><p><strong>Compute the class width.</strong> Subtract the minimum value from the maximum value to obtain the range. Divide this range by the chosen number of classes, then <em>round up</em> to a convenient number. Rounding up ensures that all observations fit neatly into the defined classes without overlap.</p></li>
<li><p><strong>Determine class limits.</strong> Choose a starting point at or slightly below the minimum value, then add the class width repeatedly to establish the remaining class boundaries. Consistent class widths make the table easier to read and interpret.</p></li>
<li><p><strong>Tally the frequencies.</strong> Count the number of observations falling into each class. Each observation should belong to exactly one class.</p></li>
</ol>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.5: Number of cavities filled (discrete data)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a dental researcher records the number of cavities filled for 40 patients in a clinic over the past month. The raw data is shown below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>3, 2, 2, 2, 3, 2, 4, 0, 2, 2, 2, 5, 2, 0, 2, 4, 1, 1, 3, 0, 1, 3, 0, 3, 1, 4, 3, 1, 3, 1, 2, 1, 2, 2, 2, 0, 0, 1, 6, 4</code></pre>
</div>
</div>
<p>We want to summarize the distribution of cavities per patient.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  class      frequency
  &lt;fct&gt;          &lt;int&gt;
1 (-0.5,0.5]         6
2 (0.5,1.5]          8
3 (1.5,2.5]         13
4 (2.5,3.5]          7
5 (3.5,4.5]          4
6 (4.5,5.5]          1
7 (5.5,6.5]          1</code></pre>
</div>
</div>
<p>Because the data are <em>counts</em>, classes of width 1 are natural and easy to interpret. Each class corresponds to an exact number of cavities (0, 1, 2, 3, and so on). The frequency distribution shows how common each count is and immediately reveals whether most patients have few cavities or whether higher counts are common.</p>
</div>
</div>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.6: Systolic blood pressure (continuous data)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Now consider a study measuring systolic blood pressure (in mmHg) for 60 adults. Unlike cavity counts, blood pressure is a <em>continuous</em> variable, so it makes sense to group values into wider intervals.</p>
<p>The 60 measurements are shown below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>132.8, 108.8, 127.1, 123.7, 115, 87.3, 114, 109.7, 126.7, 117.9, 118.9, 114, 121.7, 121.6, 86.8, 145.2, 134.2, 128.3, 112.9, 135.3, 120.1, 122.5, 104.1, 147, 125.7, 153.6, 151, 125.9, 134.7, 150.9, 117.1, 127.5, 121.2, 130, 127.7, 142.5, 133.9, 111.6, 133.7, 112.6, 107.6, 136.7, 106.9, 129.6, 112.5, 146.3, 135.7, 119, 137, 131.4, 107.5, 121.9, 111, 131.7, 115.3, 121.5, 106.5, 110.6, 127, 110</code></pre>
</div>
</div>
<p>The minimum measurement is 86.8 and the max is 153.6 which gives us a range of <span class="math display">\[
\text{max} - \text{min} = 153.6 - 86.8 = 66.8
\]</span></p>
<p>If we choose seven classes, then we find the class width to be <span class="math display">\[
\frac{\text{range}}{7}=\frac{66.8}{7}=9.5428571
\]</span></p>
<p>which we will round up to 10. We use 85 as the starting point since it is slightly below the minimum measurement. Now we can construct the intervals and find the frequencies for each.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  class     frequency
  &lt;fct&gt;         &lt;int&gt;
1 [85,95)           2
2 [95,105)          1
3 [105,115)        15
4 [115,125)        14
5 [125,135)        17
6 [135,145)         5
7 [145,155)         6</code></pre>
</div>
</div>
<p>Here, the classes span 10 mmHg intervals (e.g., 85–95, 95-105, etc.). This grouping smooths out small measurement differences and highlights the overall distribution, where most values cluster, how spread out the measurements are, and whether unusually high or low values appear.</p>
</div>
</div>
</section>
</section>
<section id="relative-and-cumulative-frequencies" class="level3">
<h3 class="anchored" data-anchor-id="relative-and-cumulative-frequencies">Relative and cumulative frequencies</h3>
<p>Raw counts are helpful, but sometimes we want to know what proportion of observations fall into each class. The <strong>relative frequency</strong> of a class is the class frequency divided by the total number of observations.</p>
<p>If you add successive relative frequencies as you move across the classes, you get the <strong>cumulative frequency</strong>, which tells you the proportion of observations less than or equal to a given class boundary. Each entry is the sum of the current class’s relative frequency and all those below it. Because it represents a running total of proportions, the cumulative frequency increases monotonically and must end at 1 (or 100%) in the final class, reflecting that all observations have been accounted for.</p>
<p>A graphical display of cumulative frequencies is called an <strong>ogive</strong> (pronounced <em>“O-jive”</em>). An ogive plots the cumulative proportion (or cumulative percentage) on the vertical axis against the class boundaries on the horizontal axis. Each point on the ogive shows the proportion of observations that are <em>less than or equal to</em> a given value.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.7: Relative and cumulative frequencies for cavity data
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can extend our cavities example to compute relative and cumulative frequencies.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">class</th>
<th style="text-align: right;">frequency</th>
<th style="text-align: right;">relative_frequency</th>
<th style="text-align: right;">cumulative_frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(-0.5,0.5]</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.150</td>
<td style="text-align: right;">0.150</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.5,1.5]</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: right;">0.350</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(1.5,2.5]</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.325</td>
<td style="text-align: right;">0.675</td>
</tr>
<tr class="even">
<td style="text-align: left;">(2.5,3.5]</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.175</td>
<td style="text-align: right;">0.850</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(3.5,4.5]</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.100</td>
<td style="text-align: right;">0.950</td>
</tr>
<tr class="even">
<td style="text-align: left;">(4.5,5.5]</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">0.975</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(5.5,6.5]</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.8: Relative and cumulative frequencies for blood pressure data
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">class</th>
<th style="text-align: right;">frequency</th>
<th style="text-align: right;">relative_frequency</th>
<th style="text-align: right;">cumulative_frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">[85,95)</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">0.0333333</td>
</tr>
<tr class="even">
<td style="text-align: left;">[95,105)</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0166667</td>
<td style="text-align: right;">0.0500000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[105,115)</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.2500000</td>
<td style="text-align: right;">0.3000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">[115,125)</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.2333333</td>
<td style="text-align: right;">0.5333333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[125,135)</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.2833333</td>
<td style="text-align: right;">0.8166667</td>
</tr>
<tr class="even">
<td style="text-align: left;">[135,145)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0833333</td>
<td style="text-align: right;">0.9000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">[145,155)</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.1000000</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="choosing-the-number-of-classes" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-number-of-classes">Choosing the number of classes</h3>
<p>Selecting an appropriate number of classes is more art than science, but a few guidelines help. Many textbooks suggest between 5 and 20 classes; an alternative rule of thumb for histograms is to use 5 to 15 bars. As the sample size grows, more classes allow finer detail, but too many classes produce a sparse table. In practice, try several class widths and see which one provides a clear picture of the data. Software like JMP and R will automatically suggest class widths, but you can adjust them manually.</p>
</section>
<section id="working-in-jmp-2" class="level3">
<h3 class="anchored" data-anchor-id="working-in-jmp-2">Working in JMP</h3>
<p>To organize quantitative data in JMP:</p>
<ul>
<li>Use <strong>Analyze → Distribution</strong> and assign your quantitative variable to the Y‑axis. JMP will display a histogram along with a frequency table showing counts, percentages, and cumulative percentages. The red triangle (▸) menu lets you change the number of bins or show the cumulative distribution.</li>
<li>To extract a frequency table without a histogram, go to <strong>Analyze → Tabulate</strong>, drag your quantitative variable to the <strong>Drop Zone for columns</strong>, and select a statistic such as <strong>N</strong> or <strong>Percent</strong>. JMP’s Tabulate platform can create grouped summaries by another variable (e.g., cavities by gender).</li>
</ul>
</section>
<section id="recap-2" class="level3">
<h3 class="anchored" data-anchor-id="recap-2">Recap</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 86%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Keyword</strong></th>
<th><strong>Definition</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Class</strong></td>
<td>An interval into which quantitative data are grouped in a frequency distribution; each class has lower and upper limits.</td>
</tr>
<tr class="even">
<td><strong>Frequency distribution</strong></td>
<td>A table that lists classes of quantitative data and the number of observations in each class.</td>
</tr>
<tr class="odd">
<td><strong>Class width</strong></td>
<td>The difference between consecutive lower class limits, computed by dividing the data range by the number of classes.</td>
</tr>
<tr class="even">
<td><strong>Relative frequency</strong></td>
<td>The fraction or percentage of observations in a class, equal to the class frequency divided by the total sample size.</td>
</tr>
<tr class="odd">
<td><strong>Cumulative frequency</strong></td>
<td>The running total of frequencies (or relative frequencies) up to a given class, used to construct an ogive.</td>
</tr>
<tr class="even">
<td><strong>Ogive</strong></td>
<td>A graph of cumulative frequencies or cumulative relative frequencies versus the upper class boundary, useful for identifying percentiles.</td>
</tr>
</tbody>
</table>
</section>
<section id="check-your-understanding-2" class="level3">
<h3 class="anchored" data-anchor-id="check-your-understanding-2">Check your understanding</h3>
<div class="callout callout-style-default callout-note callout-titled" title="Problems">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problems
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>The heights (in centimeters) of 50 adolescents undergoing orthodontic treatment are recorded. Explain how you would construct a frequency distribution for these heights. How might your choice of the number of classes affect your ability to see the shape of the distribution?</p></li>
<li><p>Differentiate between a relative frequency distribution and a cumulative frequency distribution. In what situations would you prefer to look at cumulative frequencies instead of simple frequencies?</p></li>
<li><p>Suppose a hospital’s quality control team records the time (in minutes) it takes to triage 100 emergency room patients. The times range from 1 to 28 minutes. If you decide to use eight classes in your frequency distribution, what is the class width? After building the frequency table, describe how you would create an ogive for the data.</p></li>
<li><p>A dataset contains the number of decayed teeth per child in a dental study. Why might a class width of 1 be appropriate for this frequency distribution? When might you choose a wider class width?</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Constructing a frequency distribution.</strong> List the minimum and maximum heights, decide on the number of classes (e.g., between 5 and 15), compute the class width by dividing the range by the number of classes, and set class limits starting at or below the minimum. Tally the number of heights falling into each class. Fewer classes smooth out details; more classes reveal fine structure but may result in many empty or low‑frequency intervals. Experimenting with different numbers of classes helps you see the underlying shape.</p></li>
<li><p><strong>Relative vs.&nbsp;cumulative frequency.</strong> A relative frequency distribution reports the proportion of observations in each class. A cumulative frequency distribution adds the proportions successively to show the total proportion up to each class. Cumulative frequencies are useful when you care about percentiles or thresholds—for example, determining the percentage of patients whose heights are below a certain value.</p></li>
<li><p><strong>Calculating class width and drawing an ogive.</strong> The range is 28 − 1 = 27 minutes. Dividing by eight classes gives 3.375 minutes; rounding up to 4 minutes yields a class width of 4. You would start your first class at or below 1 minute and create successive 4‑minute intervals (e.g., 0–4, 4–8, … ). After tallying frequencies, compute cumulative frequencies and plot them against the upper class boundaries to form the ogive.</p></li>
<li><p><strong>Choosing class width for count data.</strong> Decayed teeth are counted in whole numbers, so using a class width of 1 preserves each distinct count (0, 1, 2, …) and yields an easy‑to‑interpret distribution. If the counts range widely or if some counts are rare, a wider class width (e.g., grouping 4–6 teeth together) could reduce sparsity and simplify the table.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="sec-03_4" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-03_4"><span class="header-section-number">3.4</span> Histograms, Stem‑and‑Leaf Plots, and Dotplots</h2>
<blockquote class="blockquote">
<p>The purpose of [data] display is comparison (recognition of phenomena), not numbers… The phenomena are the main actors, numbers are the supporting cast. - John Tukey</p>
</blockquote>
<p>Once quantitative data are grouped into classes, we can visualize the distribution using several complementary plots. Histograms show how the data are distributed across intervals; stem‑and‑leaf plots preserve individual values while offering a quick visual summary; and dotplots display each observation as a dot. Choosing the right tool depends on your sample size, measurement scale, and the story you want to tell.</p>
<section id="histograms" class="level3">
<h3 class="anchored" data-anchor-id="histograms">Histograms</h3>
<p>A <strong>histogram</strong> is a graphical display for <em>quantitative data</em> that shows how values are distributed across a range. Like a bar chart, it uses rectangular bars, but the interpretation is fundamentally different. Each bar in a histogram represents a <em>class interval</em> of numerical values, and the height of the bar shows how many observations fall within that interval (or the proportion of observations, if relative frequencies are used).</p>
<p>Because quantitative data are measured on a <em>continuous scale</em>, the bars in a histogram <em>touch</em>. This visual continuity emphasizes that values flow smoothly from one class to the next, unlike categorical bar charts where gaps indicate distinct groups. The horizontal axis is measured in the original units of the data, while the vertical axis displays either frequency, relative frequency, or density.</p>
<p>Histograms are especially useful for revealing the <strong>shape</strong>, <strong>center</strong>, and <strong>spread</strong> of a distribution. They allow us to see whether data are symmetric or skewed, whether there are multiple peaks, and whether unusually large or small values (outliers) are present.</p>
<section id="constructing-a-histogram" class="level4">
<h4 class="anchored" data-anchor-id="constructing-a-histogram">Constructing a histogram</h4>
<p>A histogram is built directly from a frequency distribution. The steps are:</p>
<ol type="1">
<li><strong>Construct a frequency distribution</strong> using classes of equal width (see <a href="#sec-03_03" class="quarto-xref"><span>Section 3.3</span></a>).</li>
<li><strong>Label the horizontal axis</strong> with the class boundaries and the vertical axis with frequencies or relative frequencies.</li>
<li><strong>Draw adjacent rectangles</strong> whose widths equal the class widths and whose heights equal the corresponding frequencies.</li>
</ol>
<p>In a <em>density histogram</em>, the bar heights are scaled so that the <em>area</em> of each bar equals the class’s relative frequency. In that case, the total area of the histogram equals 1.</p>
<p>The number of classes (bins) strongly affects the appearance of a histogram. Too few bins oversmooth the data and hide structure; too many bins create a jagged, noisy plot. A common guideline is to use <em>between 5 and 15 bins</em>, adjusting as needed to highlight meaningful patterns rather than random variation. As with bar charts, decorative effects such as 3-D bars should be avoided, they distort perception without adding information.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.9: Resting heart rates
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a study of the resting heart rates (in beats per minute) of 100 individuals undergoing physical therapy. Resting heart rate is a <em>continuous quantitative variable</em>, so grouping values into intervals is appropriate.</p>
<p>The 100 measurements are shown below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>75, 70, 76, 80, 73, 69, 73, 69, 67, 76, 67, 56, 67, 76, 79, 68, 70, 73, 59, 89, 68, 76, 93, 75, 69, 60, 63, 70, 67, 76, 62, 85, 60, 75, 65, 60, 72, 58, 77, 78, 80, 82, 65, 67, 58, 79, 66, 71, 77, 74, 73, 60, 69, 79, 73, 79, 75, 63, 64, 70, 75, 75, 74, 81, 61, 50, 63, 67, 84, 67, 69, 64, 63, 51, 66, 78, 66, 82, 64, 65, 61, 82, 72, 62, 70, 70, 80, 62, 62, 78, 75, 63, 84, 71, 67, 62, 55, 58, 63, 72</code></pre>
</div>
</div>
<p>The minimum heart rate is 50 and the maximum is 93, giving a range of <span class="math display">\[
\text{range} = 93 - 50 = 43.
\]</span></p>
<p>Suppose we choose 10 classes. The class width is <span class="math display">\[
\frac{\text{range}}{10} = \frac{43}{10}
\]</span> which we round up to a convenient value of 5 beats per minute. We start slightly below the minimum value at 47.5 and construct the class intervals.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   class       frequency
   &lt;fct&gt;           &lt;int&gt;
 1 [47.5,52.5)         2
 2 [52.5,57.5)         2
 3 [57.5,62.5)        15
 4 [62.5,67.5)        23
 5 [67.5,72.5)        18
 6 [72.5,77.5)        21
 7 [77.5,82.5)        14
 8 [82.5,87.5)         3
 9 [87.5,92.5)         1
10 [92.5,97.5)         1</code></pre>
</div>
</div>
<p>This frequency distribution shows how heart rates accumulate across the range. From this table, we construct the histogram by drawing adjacent bars whose heights correspond to these frequencies.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.10: Daily delivery times
</div>
</div>
<div class="callout-body-container callout-body">
<p>A logistics company records the <em>delivery times</em> (in minutes) for 75 packages delivered within a city on a given day. Delivery time is a continuous quantitative variable, so we again begin by constructing a frequency distribution.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>31.5, 31.3, 27.3, 41, 46.5, 49.9, 38.1, 38.3, 50, 29.1, 28.8, 32.8, 31.8, 39, 40.7, 35.8, 47.4, 58.6, 28.8, 46.4, 37.5, 45.7, 42.3, 44.3, 51.8, 22.8, 44.5, 24.6, 41.9, 36.4, 40.7, 27.9, 52.6, 38.4, 39, 54.6, 47.5, 25.4, 52.7, 39.8, 42.5, 52.8, 34.4, 41.9, 40.1, 48.7, 54.8, 25.1, 37.5, 26.8, 61.9, 37.9, 41.3, 42.4, 52.2, 53.5, 60.7, 45.5, 42.7, 17.7, 43.6, 34.3, 43.9, 50.9, 47.6, 56.3, 21.9, 57.9, 61.5, 44.3, 39.4, 44, 49, 40, 39.2</code></pre>
</div>
</div>
<p>The minimum delivery time is 17.7 minutes and the maximum is 61.9 minutes, giving a range of <span class="math display">\[
61.9 - 17.7 = 44.2.
\]</span></p>
<p>Suppose we choose <em>8 classes</em>. The class width is <span class="math display">\[
\frac{\text{range}}{8} = \frac{44.2}{8},
\]</span> which we round up to 6 minutes. We start at 17 minutes and construct the intervals.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
  class   frequency
  &lt;fct&gt;       &lt;int&gt;
1 [17,23)         3
2 [23,29)         8
3 [29,35)         7
4 [35,41)        17
5 [41,47)        18
6 [47,53)        13
7 [53,59)         6
8 [59,65)         3</code></pre>
</div>
</div>
<p>Using this frequency distribution, we now draw the histogram.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="why-histograms-matter" class="level3">
<h3 class="anchored" data-anchor-id="why-histograms-matter">Why histograms matter</h3>
<p>Histograms transform a frequency distribution into a visual summary that highlights the <em>shape</em> of the data. They help us see where observations cluster, how variable the data are, and whether unusual values are present. Because many statistical methods rely on assumptions about distributional shape, histograms play a central role in both exploratory analysis and model checking.</p>
<section id="caution-about-number-of-classes" class="level4">
<h4 class="anchored" data-anchor-id="caution-about-number-of-classes">Caution about number of classes</h4>
<p>When constructing a histogram, the choice of the number of classes (bins) requires care. <em>Too few classes</em> oversmooth the data, hiding important features such as skewness, gaps, or multiple peaks. In contrast, <em>too many classes</em> make the histogram appear jagged and noisy, emphasizing random variation rather than meaningful structure. A well-chosen number of classes balances detail with clarity, revealing the overall shape of the distribution without distracting from its main features.</p>
<p>From Example 3.10, suppose we chose 40 classes instead of 8. The resulting histogram would look like:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>From this histogram, we cannot determine much about the structure due to the jagged shape from too many bars.</p>
<p>Suppose we chose 4 classes instead:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Here, some of the features of the data is lost since the bars span too large of a class interval. We may want to know more on how the values are distributed in these large intervals. Fortunately, most software like JMP do a good job in finding a right balance in determining the number of classes.</p>
</section>
</section>
<section id="stem-and-leaf-plots" class="level3">
<h3 class="anchored" data-anchor-id="stem-and-leaf-plots">Stem-and-leaf plots</h3>
<p>A <strong>stem-and-leaf plot</strong> is a simple display for <em>quantitative data</em> that preserves the original numerical values while providing a visual summary of the distribution. Each observation is split into two parts: a <em>stem</em>, consisting of the leading digit(s), and a <em>leaf</em>, consisting of the final digit. The stems are listed in increasing order in a column, and the leaves corresponding to each stem are written to the right.</p>
<p>Because stem-and-leaf plots retain every data value, they allow you to see the <em>shape</em>, <em>center</em>, and <em>spread</em> of the distribution and recover the original dataset if needed. This makes them especially useful for small to moderate sample sizes (typically fewer than about 100 observations), where displaying individual values is still manageable.</p>
<p>Unlike histograms, which group data into intervals and sacrifice some detail, stem-and-leaf plots show exactly where each observation falls. At the same time, the ordered stems and leaves create a visual structure that reveals clustering, gaps, skewness, and extreme values.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.11: Recovery times after knee surgery
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose an orthopedic clinic records the time (in days) for 20 patients to regain full range of motion after knee surgery. We can construct a stem-and-leaf plot as follows:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

  0 | 88899
  1 | 000002224
  1 | 5578
  2 | 14</code></pre>
</div>
</div>
</div>
</div>
<p>In a hand-drawn stem-and-leaf plot, the <em>stems</em> would represent the tens of days (e.g., 1, 2, 3), and the <em>leaves</em> would represent the ones digit. Many statistical software packages split each stem into two rows, one for leaves 0–4 and another for leaves 5–9, to make patterns easier to see.</p>
<p>From the plot, it is easy to see where most recovery times cluster and to identify unusually long recovery periods. Because the stems are ordered, the plot also highlights the overall shape of the distribution and any extreme values.</p>
<hr>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.12:  Quiz scores in a class
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose an instructor records the quiz scores (out of 100) for 80 students in an algebra course.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

  5 | 4
  5 | 9
  6 | 11234
  6 | 5556799
  7 | 0001223344
  7 | 55566666666667788888999
  8 | 000111222233334
  8 | 555777789
  9 | 00122
  9 | 5689</code></pre>
</div>
</div>
<p>Here, the stems represent the <em>tens digit</em> of the score (5, 6, 7, 8, 9), and the leaves represent the <em>ones digit</em>. The stem-and-leaf plot shows that most scores fall in the 70s and 80s, with a few higher scores in the 90s and possibly some lower scores in the 50s.</p>
</div>
</div>
</section>
<section id="when-stem-and-leaf-plots-are-most-useful" class="level3">
<h3 class="anchored" data-anchor-id="when-stem-and-leaf-plots-are-most-useful">When stem-and-leaf plots are most useful</h3>
<p>Stem-and-leaf plots are ideal when:</p>
<ul>
<li>The dataset is small enough to display individual values clearly,</li>
<li>You want both a <em>numerical listing</em> and a <em>graphical summary</em>,</li>
<li>Preserving the original data values is important.</li>
</ul>
<p>For larger datasets, stem-and-leaf plots become cluttered, and histograms or dotplots are usually more effective. However, for exploratory analysis of modest-sized samples, stem-and-leaf plots provide a powerful blend of detail and visualization.</p>
</section>
<section id="dotplots" class="level3">
<h3 class="anchored" data-anchor-id="dotplots">Dotplots</h3>
<p>A <strong>dotplot</strong> is a simple graphical display for <em>quantitative data</em> in which each observation is represented by a dot placed above a number line. When multiple observations have the same value, the dots are stacked vertically. This stacking makes frequencies visible while still preserving the individual data points.</p>
<p>Dotplots are especially useful for <em>small to moderate datasets</em>, where displaying every observation is feasible and desirable. Unlike histograms, which group values into bins, dotplots show the exact values observed. This makes it easy to identify <em>clusters</em>, <em>gaps</em>, and <em>outliers</em>, as well as to see the overall shape of the distribution.</p>
<p>Because dotplots work directly with individual values, they are flexible enough to handle both <em>discrete</em> variables (such as counts) and <em>continuous</em> variables (especially when the data are rounded). They are also quick to construct and intuitive to read, making them a popular choice for exploratory analysis and classroom demonstrations.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.13:  Yearly clinic visits
</div>
</div>
<div class="callout-body-container callout-body">
<p>Continuing the dental theme, suppose researchers record the number of clinic visits per patient during a year for 25 orthodontic patients. The variable of interest—the number of visits—is a discrete quantitative variable.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The dotplot shows that most patients had between <em>one and three visits</em>, while a few had <em>no visits</em> or as many as <em>13 visits</em>. Because each dot represents a patient, the plot makes it easy to see both the concentration of values and the less common outcomes.</p>
</div>
</div>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3.14:  Daily coffee consumption
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a workplace survey records the number of cups of coffee consumed per day by 30 employees.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>This dotplot reveals that most employees drink <em>one to three cups per day</em>, with a smaller number drinking <em>four or more cups</em> and a one employee drinking <em>none at all</em>. The stacked dots make it easy to compare frequencies while still seeing each individual’s value.</p>
</div>
</div>
</section>
<section id="when-dotplots-are-most-useful" class="level3">
<h3 class="anchored" data-anchor-id="when-dotplots-are-most-useful">When dotplots are most useful</h3>
<p>Dotplots are an excellent choice when:</p>
<ul>
<li>The dataset is small enough to display individual observations clearly,</li>
<li>Exact values matter,</li>
<li>You want to quickly identify clusters, gaps, and outliers.</li>
</ul>
<p>As datasets grow larger, dotplots can become cluttered and difficult to read. In those cases, histograms provide a more effective summary. For small to moderate datasets, however, dotplots strike a valuable balance between numerical precision and visual insight.</p>
</section>
<section id="choosing-the-right-display" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-right-display">Choosing the right display</h3>
<ul>
<li><strong>Histograms</strong> reveal the overall shape of a distribution and are most useful for moderate to large samples. They sacrifice individual data values to provide a smooth picture of the distribution.</li>
<li><strong>Stem‑and‑leaf plots</strong> preserve actual data values and work well for small to moderate samples. They quickly show the shape and allow you to recover the raw data.</li>
<li><strong>Dotplots</strong> also preserve individual values and are easy to interpret for small datasets; they can handle discrete counts and continuous measurements.</li>
</ul>
</section>
<section id="working-in-jmp-3" class="level3">
<h3 class="anchored" data-anchor-id="working-in-jmp-3">Working in JMP</h3>
<p>In JMP:</p>
<ul>
<li>To create a histogram or stem‑and‑leaf plot, use <strong>Analyze → Distribution</strong>. For stem‑and‑leaf plots, JMP automatically splits stems if needed and prints the “leaf unit.” The red triangle (▸) menu lets you toggle between histogram and stem‑and‑leaf views.</li>
<li>To build a dotplot, open <strong>Graph Builder</strong>, drag your quantitative variable to the X‑axis, and choose “Dot Plot” from the element palette.</li>
</ul>
</section>
<section id="recap-3" class="level3">
<h3 class="anchored" data-anchor-id="recap-3">Recap</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 85%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Keyword</strong></th>
<th><strong>Definition</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Histogram</strong></td>
<td>A graph of adjacent rectangles representing classes of a quantitative variable; the horizontal axis is numeric and the bars touch.</td>
</tr>
<tr class="even">
<td><strong>Relative frequency histogram</strong></td>
<td>A histogram in which the height of each bar shows the relative frequency (proportion) in that class, so the sum of the bar heights equals 1.</td>
</tr>
<tr class="odd">
<td><strong>Stem‑and‑leaf plot</strong></td>
<td>A display that splits each data value into a stem (leading digits) and a leaf (trailing digit), preserving the original data.</td>
</tr>
<tr class="even">
<td><strong>Dotplot</strong></td>
<td>A plot that places a dot above each data value on a number line, with stacked dots representing repeated values.</td>
</tr>
</tbody>
</table>
</section>
<section id="check-your-understanding-3" class="level3">
<h3 class="anchored" data-anchor-id="check-your-understanding-3">Check your understanding</h3>
<div class="callout callout-style-default callout-note callout-titled" title="Problems">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problems
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Explain why a histogram is drawn with adjacent bars touching. How does this design reinforce the type of variable being plotted?</p></li>
<li><p>For a set of 15 recovery times (in days) after a dental procedure, would you prefer a histogram, a stem‑and‑leaf plot, or a dotplot? Justify your choice.</p></li>
<li><p>In a stem‑and‑leaf plot, what do the stems and leaves represent? Why might you choose to split the stems into two rows for certain datasets?</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Why bars touch.</strong> The bars in a histogram are adjacent because the underlying variable is continuous, and there are no gaps between the classes. Drawing the bars together emphasizes that each class covers an interval on the number line; a gap would incorrectly suggest a break between values.</p></li>
<li><p><strong>Choosing a plot for 15 observations.</strong> For a sample of 15 recovery times, a stem‑and‑leaf plot or dotplot would preserve the individual values and make it easy to see exact times. A histogram could also work, but with so few observations its appearance would depend heavily on the chosen bin width. Stem‑and‑leaf plots are especially useful here because they reveal the shape and extremes while retaining the data.</p></li>
<li><p><strong>Interpreting stems and leaves.</strong> In a stem‑and‑leaf plot, the stem contains the leading digits of each number and the leaf is the final digit. Splitting stems into two rows—one for leaves 0–4 and one for leaves 5–9—provides more detail and smooths out long runs of leaves, making the distribution easier to read.</p></li>
</ol>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>